### ISSUE TITLE
Adding a team to a User gives an error on save

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#8] opened 2015-11-19 18:12 UTC
If you try to add a user to a “Team” you get an error on Save and it doesn’t show it in the table.  Something about the Amino User instance isn’t valid 422.

You can go to the Teams page and add Users to the Team from there as a workaround.

**Comment by bmcdougald** [comment] 2016-01-28 15:09
#97 was marked as a dupe of this issue.  I will be closing that issue as duplicate.

[description of related behavior from #97 ]
Once users are created, you cannot change their role or team association it seems. When you click on save for the changes, the depot returns red warning/failure balloon tips and the attempted change is ignored.

**Comment by michaelsframe** [comment] 2016-03-08 20:59
fixed, merged to develop  1b4d30578a1ce8f40fca82999c0d9f42148c507a

**Closed as completed by michaelsframe** 2016-03-08 20:59 UTC
Labels: bug
