### ISSUE TITLE
Depot: Domain Items cannot be deleted

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#156] opened 2016-01-27 20:52 UTC
Attempting to delete an item via the trash icon brings up the confirmation but then fails to load the table (long progress bar similar to edit/delete items in other tables).  When you refresh or log out and back in the item still shows in the table that you tried to delete.

**Comment by michaelsframe** [comment] 2016-01-28 22:35
dupe of #99 (same root cause, missing Domain Item ID). closing to resolve there.

**Closed as completed by michaelsframe** 2016-01-28 22:35 UTC
Labels: bug
