### ISSUE TITLE
Adding new Teams, Domains or Trails to the Depot requires restart to see them in the toolbar

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#44] opened 2015-12-16 18:29 UTC
If you add any of these items via the web interface for the depot, you won't see them in the pulldowns for the plugin toolbar until you log out then back in again

**Comment by bwhiteman** [comment] 2015-12-16 18:32
This is a duplicate of #6

**Closed as completed** 2015-12-16 18:39 UTC
Labels: bug, duplicate
