### ISSUE TITLE
Depot: Trails: restrict by user Teams

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#78] opened 2016-01-07 04:21 UTC
A user should only see the Trails for teams that they belong to, not all trails as is currently displayed.

While cleaning up the view we can remove Team, Scrape, and Feeds from the default Trail List.

**Comment by bmcdougald** [comment] 2016-01-11 17:46
Looks like this is working as intended.  I can pick a different team in the toolbar and only the trails and domains which are assigned to that team populate the respective picklists in the toolbar.

**Closed as completed by bmcdougald** 2016-01-11 17:46 UTC
Labels: enhancement

**Comment by michaelsframe** [comment] 2016-01-11 18:15
To clarify, this is in the Depot Trails page, not in the toolbar.
